# Author: Ivonne Giske <ivonne.giske@fu-berlin.de> or <ivonne.giske@student.htw-berlin.de>
# This script was written for my Bachelorthesis concerning data quality in the Herbonauts project.
# The code draws a sample of x voucher_ids out of completed missions chosen by me that hold validated data generated by Herbonauts over the last 6 years.
# The script assumes that a folder with .csv files that hold the validated entries per mission are located in a folder called 'Missionen'.
# These CSV files are assumed to be named after the ID of the mission they contain. Here the ID was chosen to match the mission ID in the error analysis database.
# To change the size of the sample, please change the variable 'sampleSize'.
# Two .csv documents will be created by this code, one holding all validated entries of all missions which is the basis of the sample.
# Another one holding the sample itself, consisting of one column with voucher_ids and one column with mission_id. This document can be imported into the error analysis database.

import os

import pandas as pd

sample_size = 10
RELATIVE_PATH_IN_MISSIONS = "../input/missions/"
RELATIVE_PATH_OUT = "../output/"


for filename in os.listdir(RELATIVE_PATH_IN_MISSIONS):
    if filename.endswith(".csv"):
        mission_specimen_list = pd.read_csv(
            RELATIVE_PATH_IN_MISSIONS + filename, sep=";"
        )
        if mission_specimen_list.columns[3] != "mission - id":
            mission_id = filename[:-4]
            mission_specimen_list.insert(
                3, "mission - id", mission_id, allow_duplicates=False
            )
        else:
            voucher_ids = mission_specimen_list[["specimen - code", "mission - id"]]
            voucher_ids.to_csv(
                RELATIVE_PATH_OUT + "list_of_all_voucher_ids.csv",
                sep=";",
                header=False,
                index=False,
                mode="a",
            )
    else:
        continue

all_vouchers_list = pd.read_csv(
    RELATIVE_PATH_OUT + "list_of_all_voucher_ids.csv", sep=";", header=None
)
sample = all_vouchers_list.sample(n=sample_size)
sample.to_csv(
    RELATIVE_PATH_OUT + "sample_example.csv",
    sep=";",
    header=["voucher_ID", "mission_id"],
    index=False,
)
